In [3]:
import numpy as np
a = np.array([(i+1)*np.ones(3) for i in range(3)])
x,y,z = a
print(x,y,z)
print(a)


[1. 1. 1.] [2. 2. 2.] [3. 3. 3.]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [7]:
a

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [18]:
np.random.rand(4,3)

array([[0.17652864, 0.36073239, 0.1439719 ],
       [0.09419533, 0.22795739, 0.99399358],
       [0.0563945 , 0.90493094, 0.96556797],
       [0.65662998, 0.05488946, 0.12410743]])

In [22]:
x,y,z = np.random.rand(3,10)
x

array([0.8465425 , 0.15291922, 0.78385684, 0.88414628, 0.30473319,
       0.4893171 , 0.05008762, 0.71408697, 0.75242352, 0.00916065])